// Bindings generated by `windows-bindgen` 0.59.0

#![allow(
    non_snake_case,
    non_upper_case_globals,
    non_camel_case_types,
    dead_code,
    clippy::all
)]

pub mod Windows {
    pub mod Win32 {
        pub mod Foundation {
            #[repr(C)]
            #[derive(Clone, Copy, Debug, PartialEq)]
            pub struct SYSTEMTIME {
                pub wYear: u16,
                pub wMonth: u16,
                pub wDayOfWeek: u16,
                pub wDay: u16,
                pub wHour: u16,
                pub wMinute: u16,
                pub wSecond: u16,
                pub wMilliseconds: u16,
            }
            impl Default for SYSTEMTIME {
                fn default() -> Self {
                    unsafe { core::mem::zeroed() }
                }
            }
        }
        pub mod System {
            pub mod SystemServices {
                pub const TIME_ZONE_ID_DAYLIGHT: u32 = 2u32;
                pub const TIME_ZONE_ID_STANDARD: u32 = 1u32;
                pub const TIME_ZONE_ID_UNKNOWN: u32 = 0u32;
            }
            pub mod Time {
                #[inline]
                pub unsafe fn GetDynamicTimeZoneInformation(
                    ptimezoneinformation: *mut DYNAMIC_TIME_ZONE_INFORMATION,
                ) -> u32 {
                    windows_targets::link!("kernel32.dll" "system" fn GetDynamicTimeZoneInformation(ptimezoneinformation : *mut DYNAMIC_TIME_ZONE_INFORMATION) -> u32);
                    unsafe { GetDynamicTimeZoneInformation(ptimezoneinformation as _) }
                }
                #[repr(C)]
                #[derive(Clone, Copy, Debug, PartialEq)]
                pub struct DYNAMIC_TIME_ZONE_INFORMATION {
                    pub Bias: i32,
                    pub StandardName: [u16; 32],
                    pub StandardDate: super::super::Foundation::SYSTEMTIME,
                    pub StandardBias: i32,
                    pub DaylightName: [u16; 32],
                    pub DaylightDate: super::super::Foundation::SYSTEMTIME,
                    pub DaylightBias: i32,
                    pub TimeZoneKeyName: [u16; 128],
                    pub DynamicDaylightTimeDisabled: bool,
                }
                impl Default for DYNAMIC_TIME_ZONE_INFORMATION {
                    fn default() -> Self {
                        unsafe { core::mem::zeroed() }
                    }
                }
                pub const TIME_ZONE_ID_INVALID: u32 = 4294967295u32;
            }
        }
    }
}
